name: elsner_practical
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.22.3
  connectivity: ^0.4.6+2
  dio: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
